### PR TITLE
Add categories (goals) to SDG targets

### PR DESCRIPTION
**Pull request by andylolz**
There’s a link between these two codelists, which it’s useful to be able to see on the reference site and elsewhere. The DAC (replicated) codelist includes this link as category elements.

### CODE REVIEW

**Comment by andylolz** [comment]
Cool – thanks for taking a look Matt!

So I sent the equivalent PR upstream here: IATI/IATI-Codelists-NonEmbedded#304.

So for the IATI reference site, it adds references from SDG targets to their respective SDG goals:
http://sdg-categories-iati-codelists-nonembedded-refbot.surge.sh/codelists/UNSDG-Targets/#codes

On https://codelists.codeforiati.org, this would add a reference in the description, and categories, similar to those shown on [the Sector codelist](https://codelists.codeforiati.org/Sector/).

**Comment by matmaxgeds** [comment]
Thanks - good to see that it is used elsewhere (Sectors).....part of me feels that this hints about how the SDG Indicators (the third level, non-replicated to date) codelist should be setup.

**Comment by andylolz** [comment]
Yep, agreed. I’m unsure why this wouldn’t also be replicated.

**Comment by andylolz** [comment]
Ace – so the categories are now shown here:
https://codelists.codeforiati.org/UNSDG-Targets/

**Pull request merged**
